### ISSUE TITLE
Configure @hackoregon/component-library for use in other contexts

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#398]
For some upcoming projects, and also to provide any open-source users with a better experience, it'd be useful to be able to use the component-library outside of the Civic mono-repo without extensive customization. One example is something I put together using Glitch for our [OSCON Workshop]( https://glitch.com/edit/#!/alabaster-mouth?path=README.md:1:0)

In order for this to happen, I think we need three things to happen:
- [ ] Ensure component-library has all of the appropriate dependencies - there are some missing dependencies hidden by the mono-repo structure
- [ ] Determine publishing workflow for component-library package. I have the appropriate npm credentials we need to publish updated packages.
- [ ] (could be done later) Handle instances of window appropriately so that server-side rendering would work

**Comment by jaronheard** [comment]
#444 addressed
