### ISSUE TITLE
Convert bar chart to VictoryCharts

### ISSUE THREAD

**Issue by DingoEatingFuzz** [hackoregon/civic#44]
We are moving from Recharts to VictoryCharts.

The existing BarChart component needs to be converted to the VictoryCharts equivalent: https://formidable.com/open-source/victory/docs/victory-bar/

The purpose of having our components wrap VictoryCharts is to prescribe stylistic choices, such as colors, line weight, spacing, etc.

**Todo:**
- [x] Add VictoryCharts as a dependency
- [x] Rewrite the BarChart component
- [x] Add unit tests
- [x] Update the BarChart story

The basic bar chart should look like this, and have all of the components shown in this chart.
<img width="517" alt="vb no toolkit" src="https://user-images.githubusercontent.com/7065695/39656267-74bb46a6-4fb3-11e8-9af8-1c841a784cdf.png">
Shown with common tooltip component:
<img width="501" alt="vb tooltip" src="https://user-images.githubusercontent.com/7065695/39656268-74d23334-4fb3-11e8-8c18-ee8fc1bec2eb.png">

Generally, I'm expecting that the color and font styling will be inherited from a common VictoryTheme, so don't worry about the color and font for this issue.

In addition to what is shown, BarChart should have the following features:
- [ ] Accessibility description
- [x] Responsive

**Comment by jaronheard** [comment]
The basic bar chart should look like this, and have all of the components shown in this chart.
![image](https://user-images.githubusercontent.com/7065695/39156851-de985b7c-470c-11e8-8ddc-23d064acf8c0.png)

Generally, I'm expecting that the color and font styling will be inherited from a common VictoryTheme, so don't worry about the color and font.

In addition to what is shown, BarChart should have the following features:
Accessibility description
Responsive

**Comment by jaronheard** [comment]
Updated bar chart design to latest version showing common tooltip component

**Comment by AlexanderNull** [comment]
Closing out without accessibility as we have #122 to track it across all components
