### ISSUE TITLE
Convert line chart to VictoryCharts

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#48]
We are moving from Recharts to VictoryCharts. See also issue #44.

The existing LineChart component needs to be converted to the VictoryCharts equivalent: https://formidable.com/open-source/victory/docs/victory-bar/

The purpose of having our components wrap VictoryCharts is to prescribe stylistic choices, such as colors, line weight, spacing, etc.

**Todo:**
- [x] Add VictoryCharts as a dependency
- [x] Rewrite the LineChart component
- [x] Add unit tests
- [x] Update the LineChart story

The basic line chart should look like this, and have all of the components shown in this chart.
<img width="515" alt="lc no tooltip" src="https://user-images.githubusercontent.com/7065695/39656140-ad36b3fe-4fb2-11e8-935a-336486b28b65.png">
Shown with common tooltip component:
<img width="514" alt="lc tooltip" src="https://user-images.githubusercontent.com/7065695/39656139-ad17ee88-4fb2-11e8-8a1f-0297b265ad2f.png">

Generally, I'm expecting that the color and font styling will be inherited from a common VictoryTheme, so don't worry about the color and font for this issue.

In addition to what is shown, BarChart should have the following features:
- [ ] Accessibility description
- [x] Responsive

**Comment by jaronheard** [comment]
I've updated the design of the line chart to the latest version that shows with and without the common tooltip component.

**Comment by AlexanderNull** [comment]
Accessibility tracked in https://github.com/hackoregon/civic/issues/122
