### ISSUE TITLE
Convert scatter plot to VictoryCharts

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#49]
We are moving from Recharts to VictoryCharts. See also issue #44.

The existing ScatterPlot component needs to be converted to the VictoryCharts equivalent: https://formidable.com/open-source/victory/docs/victory-bar/

The purpose of having our components wrap VictoryCharts is to prescribe stylistic choices, such as colors, line weight, spacing, etc.

**Todo:**
- [x] Add VictoryCharts as a dependency
- [x] Rewrite the ScatterPlot component
- [x] Add unit tests
- [x] Update the ScatterPlot story

The basic scatterplot should look like this, and have all of the components shown in this chart.
<img width="530" alt="sp no tooltip" src="https://user-images.githubusercontent.com/7065695/39642284-214c229c-4f86-11e8-9e96-36f2757a1a01.png">
<img width="520" alt="sp tooltip" src="https://user-images.githubusercontent.com/7065695/39642285-216fb004-4f86-11e8-9828-f7e10ff66bd9.png">

Generally, I'm expecting that the color and font styling will be inherited from a common VictoryTheme, so don't worry about the color and font for this issue.

In addition to what is shown, Scatterplot should have the following features:
- [x] Accessibility description
- [x] Responsive

**Comment by jaronheard** [comment]
I've updated the design in the original issue. The tooltip shown is addressed in #65.

**Comment by jaronheard** [comment]
#130 addresses
