### ISSUE TITLE
Convert RechartsPie to VictoryCharts

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#50]
We are moving from Recharts to VictoryCharts. See also issue #44.

The existing pie chart component needs to be converted to the VictoryCharts equivalent: https://formidable.com/open-source/victory/docs/victory-bar/

The purpose of having our components wrap VictoryCharts is to prescribe stylistic choices, such as colors, line weight, spacing, etc.

Our existing pie component was used in:
http://housing.civicpdx.org
http://emergency-response.civicpdx.org

The pie chart component in VictoryCharts should replicate the functionality of these components.

**Todo:**
- [x] Add VictoryCharts as a dependency
- [x] Rewrite the Pie component
- [x] Add unit tests
- [x] Update the Pie story
- [x] Review all packages that already use the Pie component for regressions

The basic pie chart should look like:
<img width="346" alt="screen shot 2018-04-23 at 4 39 26 pm" src="https://user-images.githubusercontent.com/7065695/39158507-50efe110-4715-11e8-8ff0-9f60f0029179.png">

Generally, I'm expecting that the color and font styling will be inherited from a common VictoryTheme, so don't worry about the color and font for this issue.

In addition to what is shown, the pie chart should have the following features:
- [ ] Accessibility description
- [x] Responsive

**Comment by AlexanderNull** [comment]
- [ ] Determine all components that use Pie or RechartsPie components
- [ ] Settle on interface for Pie components
- [ ] Make test file & determine if shallow mount tests are adequate
- [ ] Write component shape determining test
- [ ] import victory charts to file and make basic pie chart with fake data
- [ ] bring in properties from interface above
- [ ] integrate tooltip component

**Comment by AlexanderNull** [comment]
@jaronheard Have the required properties (knobs on story) been worked out? We have a legend in the mock up above so we're assuming the consumers of this component don't want to manually add a legend themselves. We're thinking the new pie chart has something like "includeLegend" and "includeTitle" (for the old style where there was a title in the center). Is this boolean good for whether we include the legend component (probably a reusable legend for use in other charts)? What about the title, that one's probably best to just include/exclude based upon if a title was provided at all.

**Comment by AlexanderNull** [comment]
Ran through the project, RechartsPie is used in a few places but luckily the Pie component is only used in the storybook. Going to move forward with converting the Pie component.

**Comment by AlexanderNull** [comment]
Looks like VictoryPie doesn't work as well with Label/Legend components as other Victory chart types.  Going with a v1 that doesn't contain a legend but does contain individual labels for now.

**Comment by AlexanderNull** [comment]
Closing out without accessibility as we have #122 to track it across all components
