### ISSUE TITLE
Improve code quality

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#515]
This epic tracks progress for improving code quality through linting and automated formatting:

- [x] Run prettier on project #465 
- [x] Implement prettier hook #467 
- [x] Lint component library #468 
- [x] Lint 2018 package #517  
- [x] Lint 2018-disaster-resilience package #518 
- [x] Lint 2018-transportation-systems package #519
- [x] Lint 2018-housing-affordability package #520 
- [x] Lint 2018-neighborhood development package #521
- [x] Lint 2018-local-elections package #522 
- [x] Implement linting hook #523
- [x] Lint convenience packages #592 

**After Demo Day list**
Add prettier and linting checks to CI #591
Lint 2017 project #593 
Assorted linting follow ups, listed below

**Assorted follow ups**
Enable and fix linting for Disaster Resilience Quiz Card (WhatCanYouDoToPrepare)
