### ISSUE TITLE
Implement and document CSS-in-JS best practices for CIVIC

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#556]
From our [Front-End Charter](https://docs.google.com/document/d/1Gus-13If_pHBgq4uFqZFm4YEnUugyjFRuEejmmhxeno), one of our tactical goals is to determine CSS-in-JS best practices

We'd like to have consistent pattern of how we use CSS-in-JS across CIVIC, so that CIVIC developers, from newcomers to long-time contributors, have patterns to follow.

The items below document some of the components of this epic. If this is an epic that someone wants to take ownership over, please feel empowered to do that!

**Complete emotion 10 upgrade:**
- [ ] Remove other libraries, e.g. styled-components #546 
- [ ] Replace className and cx usage with css prop #548 

**Determine and document best practices for using emotion:**
- [ ] Steps TBD

**Known current issues:**
- [ ] Main shared css usage is [global.styles.css](https://github.com/hackoregon/civic/blob/master/packages/component-library/assets/global.styles.css), which is not using Emotion.
- [ ] No consistent pattern for passing custom styling to components (could be extended to #433)
- [ ] No common place for shared styling
- [ ] No common place for colors (currently stored in the VictoryTheme for data visualization components [here](https://github.com/hackoregon/civic/blob/master/packages/component-library/src/VictoryTheme/CivicVictoryTheme.js)
