### ISSUE TITLE
Add a data table component to the component library

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#66]
Our component library needs a data table.

The data table should have the following properties:
Ability to sort
Ability to filter
Show a default number of rows, but able to expand the number of rows
Categories for columns, similar to "STATISTICAL +/-" in the picture below

Should look kind of like this, but follow the style guide:
<img width="253" alt="screen shot 2018-04-30 at 7 51 46 pm" src="https://user-images.githubusercontent.com/7065695/39459406-0d8fa6da-4cb0-11e8-9db1-ee316924a2d2.png">

[Civic-Style-Guide-v1.0.pdf](https://github.com/hackoregon/civic/files/1962881/Civic-Style-Guide-v1.0.pdf)

**Todo:**
- [x] Add any needed dependencies
- [x] Write the DataTable component
- [ ] Add unit tests
- [x] Update the DataTable story

**Comment by dsdemaria** [comment]
I can take this one.

**Comment by jaronheard** [comment]
@dsdemaria Are you still working on this?

**Comment by jaronheard** [comment]
I had a thought on this component. It could makes sense to break this down into two components, at least:
DataCell - for each individual cell in the table
DataTable - this component allows sorting and organizes DataCells

That way if we wanted to add functionality or build other Cell components and organize them in a data table, we could.

I'm not totally convinced that this is the way to go, so feel free to discuss!

**Comment by dsdemaria** [comment]
I like the idea of isolating cells. I have also isolated the header and row so we can pass in custom components for those.

**Comment by jaronheard** [comment]
Awesome 👏

**Comment by dsdemaria** [comment]
Got a pr up for this. I'll add tests at a later time. I can improve the storybook documentation and/or add more functionality as needed.

**Comment by jaronheard** [comment]
#230 addressed. Pretty excited to build a card using this component!
