### ISSUE TITLE
Task choosing screen

### ISSUE THREAD

**Issue by Dianna** [hackoregon/civic#698]
It's the map part of this thing, don't worry about design, that'll happen later:

<img width="828" alt="Screen Shot 2019-08-07 at 8 47 27 PM" src="https://user-images.githubusercontent.com/10056079/62673791-a057a280-b954-11e9-9c64-0218b563bdea.png">

### Create a map component for the upper screen. It must support:
POC: proof of concept, make sure that any components are part of the upper screen as the interactive part of the screen will be developed simultaneously.

- [x] (#711) **preventing ALL INTERACTION**. This needs to be a strictly visual element
- [x] (#712) **showing images / icons** to correspond to a given type of task and an icon above indicating completed state
- [x] (#713) **panning** to an input latitude and longitude (of a selected task)
  - POC: a dropdown or buttons for now
- [x] (#714) **zooming** into and out of a task location over a duration
  - POC: buttons to zoom into / out of an object that has been panned to
- [x] (#711) **looking at from an angle** (like you’re just a bit above the buildings)
  - POC: programatically set the view angle
- [x] (#715) **map layers** to give an idea of the landscape (rather than just google maps-esque, we should be able to make this a bit more "game" like)

#### Components
Hack Oregon has a number of map components available in the `component-library` already, which are documented in our [Storybook](https://hackoregon.github.io/civic/?path=/story/*)

- `BaseMap` - our main map component, which uses react-map-gl and is used in concert with all of our DeckGL overlays. A lot of the items above should be doable just by passing the proper props to `BaseMap`. BaseMap uses Mapbox styles - right now, there are just a light style, and a dark style. We'll want to add a game style. Here's an [article](https://blog.mapbox.com/design-a-location-based-game-map-with-mapbox-studio-8cf47528fa80) about the process of creating a game-like Mapbox style. 
- `IconMap` - this map shows icons on map using DeckGL's IconLayer. The design of this component leaves a lot to be desired, so feel free to create a new component with a simplified API.

#### Implementations
Our [Storybook](https://hackoregon.github.io/civic/?path=/story/*) is one of the best places to see example implementations of our map components, but here a few more:

- [No interaction, geocoder](http://civicplatform.org/cards/you-and-your-neighbors-in-the-earthquake)
- [Updating map overlays through passing updated props](http://civicplatform.org/cards/explore-urban-campsite-sweeps)
- [Civic Sandbox](http://civicplatform.org/sandbox)

#### People
- @mendozaline is our resident front-end map component expert
- @Kristin-Sellers implemented our light theme Mapbox style

**Comment by Dianna** [comment]
Completed
