### ISSUE TITLE
Create the match-lock interface

### ISSUE THREAD

**Issue by Dianna** [hackoregon/civic#699]
### This will be the main interface mechanism for the game
The part in the red box:

<img width="820" alt="Screen Shot 2019-08-02 at 10 41 08 AM" src="https://user-images.githubusercontent.com/10056079/62388443-2ff2f080-b512-11e9-9679-a11924bca4c6.png">

### Create the match lock component
POC: proof of concept, make sure that any components are part of the upper screen as the interactive part of the screen will be developed simultaneously.

- Completed selection: note that many items may be selected at once and could complete at the same or different times.
  - [ ] Good item: fly to upper part of screen and then disappear and be removed from the DOM
  - [ ] Bad item: fly off the bottom of the screen and then disappear and be removed from the DOM
  - [ ] Multiple good items:
    - ONLY APPLIES TO ONE **TYPE** OF GOOD ITEM AT A TIME.
    - when second of good item type is chosen all items of that type grow 1.5x in size (size is just POC). It and any other items of the type that are selected will have their radial gauge start at the same place as the initially touched orb
    - on selection complete all the items that were selected fly to the top of the screen

**Comment by Dianna** [comment]
Janice I've assigned the whole epic to you, but that doesn't mean you're alone in figuring it out! We can create smaller issues as spinoffs and reference them in the epic as necessary.
