### ISSUE TITLE
Task Solving Screen

### ISSUE THREAD

**Issue by Dianna** [hackoregon/civic#701]
### Breathe life into this:

![IMG-7483](https://user-images.githubusercontent.com/10056079/62390413-0f796500-b517-11e9-9054-f675071ee9c4.JPG)

### Create the Task Solving screen
Summary: this screen consists of 3 layout elements. The task visualization at the top, the duration bar below, and the match-lock component below that. It will eventually incorporate sound elements as well.

NOTE: The task ends when the duration bar runs out OR the players reach the required number of the required item type (e.g. a fire requires 5 uses of the fire extinguisher, when a player picks the 5th fire extinguisher the task is complete)
  - [x] Complete on duration
  - [x] (#709) Complete on final item selection

- [x] (#710) Top screen
  - Show the task description (task.text?)
  - task.image (add a random image from the web for now, have fun but keep it kid friendly)
  - Show the number of correct choices relative to the number required (e.g. in the picture above the user had chosen 1 first aid item of the 5 required to complete the task)

- Duration bar
  - [x] should last the duration of the task

- Match lock: **TBD**
  - [x] Show all _types_ of items in the kit that the user selected during the build kit chapter. They are infinitely available (e.g. user chose water but not food in the build kit chapter—the user may choose as much water as they could possibly want from the match-lock interface, but the option for food isn't even shown) (blocked by #699 #708)
  - Completed selection:
    - [x] required item: TBD
    - [ ] "bonus" item: TBD
    - [x] When the target number of required items is reached the task ends

- Sound: **TBD**
    - [ ] Backtrack: TBD
    - [ ] Task content: TBD

**Comment by Dianna** [comment]
Completed ages ago, not sure which PR
