### ISSUE TITLE
Create frozen match-lock interface

### ISSUE THREAD

**Issue by Dianna** [hackoregon/civic#735]
### This will be the voting interface for the Task selection part of the game

<img width="931" alt="Screen Shot 2019-08-07 at 11 02 15 AM" src="https://user-images.githubusercontent.com/10056079/62653325-31f1f080-b912-11e9-98bd-9d086d574974.png">

### Create the vote version of the match lock component
POC: proof of concept, make sure that any components are part of the upper screen as the interactive part of the screen will be developed simultaneously.

- Start selection of orb:
  - [x] Radial gauge just like match-lock

- Completed selection: note that many items may be selected at once and could complete at the same or different times.
  - [ ] (#699) Good item: same as match-lock
  - [ ] (#700) Bad item: same as match-lock
  - [ ] (#705) Multiple good items: same as match-lock
  - [ ] **DIFFERENT THAN MATCH-LOCK** An inactive version of the orb should remain behind in the interface
  - [ ] **DIFFERENT THAN MATCH-LOCK** When the animation completes, the inactive orb should flip like a coin and reveal a replacement task orb in its place.
