### ISSUE TITLE
Create HorizontalBarChart component

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#83]
A new HorizontalBarChart component needs to be written using VictoryCharts:
https://formidable.com/open-source/victory/docs/victory-bar/

The purpose of having our components wrap VictoryCharts is to prescribe stylistic choices, such as colors, line weight, spacing, etc.

**Todo:**
- [x] Add VictoryCharts as a dependency
- [x] Write HorizontalBarChart component
- [x] Add unit tests
- [x] Update the HorizontalBarChart story

The basic horizontal bar chart should look like this, and have all of the components shown in this chart.
<img width="308" alt="hb no toolkit" src="https://user-images.githubusercontent.com/7065695/39656425-87f04446-4fb4-11e8-8923-ba8b060845e0.png">
Shown with common tooltip component:
<img width="302" alt="hb toolkit" src="https://user-images.githubusercontent.com/7065695/39656429-8ce1d7c6-4fb4-11e8-82d2-34067b596ecb.png">

Generally, I'm expecting that the color and font styling will be inherited from a common VictoryTheme, so don't worry about the color and font for this issue.

In addition to what is shown, HorizontalBarChart should have the following features:
- [x] Accessibility description
- [x] Responsive

**Comment by AlexanderNull** [comment]
Adding in unit tests

**Comment by jaronheard** [comment]
#267 and others addressed
